import nontrigonometric_harmonic_analysis_involving_wavelets_theorem_canonical_lane_mathlib.GateLemmas
import nontrigonometric_harmonic_analysis_involving_wavelets_theorem_canonical_lane_mathlib.FinalTheorem
